### ISSUE TITLE
支持else吗

### ISSUE THREAD

**Issue by yesm1994** [HaoyCn/gulp-html-tpl#2]
在readme 只看到 {{if a}}{{/if}}, 支持else 或者not defined 的用法吗？

**Comment by HaoyCn** [comment]
具体支持什么格式，是按你指定的模板渲染库来的。比如在 Demo 里是 art-template，那就支持其语法。

**Comment by yesm1994** [comment]
cool, 谢谢 @HaoyCn 
在这里找到了文档
https://aui.github.io/art-template/docs/syntax.html#Output
